name: Shape Shifter Email

on:
  schedule:
    - cron: "0 7 * * *"  # Runs every day at 7 AM UTC
  workflow_dispatch:       # Allows manual triggering of the workflow

jobs:
  send_email:
    runs-on: ubuntu-latest  # GitHub uses 'ubuntu-latest' as its available runner; Debian itself is not directly available

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the latest Python 3.x version

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run workout program
        env:
          MAILTRAP_USERNAME: ${{ secrets.MAILTRAP_USERNAME }}
          MAILTRAP_PASSWORD: ${{ secrets.MAILTRAP_PASSWORD }}
        run: python3 main.py

